services:
  - type: web
    name: steals-brothers-website
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python api/index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8080
